position: 4
label: 'Docker'
collapsible: true # make the category collapsible
collapsed: true # keep the category open by default
className: red
link:
  type: generated-index
  title: Docker case overview
customProps:
  description: This description can be used in the swizzled DocCard
