FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

# Install `Python 3.10` and `pip`
RUN apt update && apt upgrade -y && apt install -y \
        curl \
        build-essential \
        software-properties-common \
    && add-apt-repository ppa:deadsnakes/ppa \
    && apt update && apt upgrade -y \
        python3.10 \
        python3.10-distutils \
        python3.10-dev \
    && update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.10 1 \
    && rm -rf /var/lib/apt/lists/*

RUN curl -sSL https://bootstrap.pypa.io/get-pip.py -o get-pip.py && python3.10 get-pip.py && rm get-pip.py

# Install `Docker CE CLI` and `Docker Compose`(Debian or Ubuntu), refer to: https://docs.docker.com/engine/install/ubuntu/
RUN apt update && apt install -y \
        apt-transport-https \
        ca-certificates \
        curl \
        gnupg \
        lsb-release \
    && install -m 0755 -d /etc/apt/keyrings \
    && curl -fsSL https://download.docker.com/linux/$(lsb_release -is | tr '[:upper:]' '[:lower:]')/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg \
    && chmod a+r /etc/apt/keyrings/docker.gpg \
    && echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/$(lsb_release -is | tr '[:upper:]' '[:lower:]') $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null \
    && apt update && apt install -y \
        docker-ce-cli \
        docker-compose-plugin \
    && rm -rf /var/lib/apt/lists/*

# Install tools like: `git`,...etc
RUN apt update && apt install -y \
        git \
    && rm -rf /var/lib/apt/lists/*

# Install Python packages
RUN pip install --no-cache-dir --upgrade pip \
    && pip install --no-cache-dir \
        bpython \
        pytest \
        black
# Note: we had to merge the two "pip install" package lists here, otherwise the last "pip install" command in the OP may break dependency resolution…

COPY docker-entrypoint.sh /
RUN chmod +x /docker-entrypoint.sh

ENTRYPOINT [ "/docker-entrypoint.sh" ]

CMD [ "sleep", "infinity" ]